project_id = "fepxacqrrjvnvpgzwhyr"

[functions.blockchain-certify]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.send-system-notification]
verify_jwt = false

[functions.send-prospecting-email]
verify_jwt = false

[functions.send-test-email]
verify_jwt = false

[functions.translate-text]
verify_jwt = false

[functions.gmail-send-email]
verify_jwt = false

[functions.brevo-templates]
verify_jwt = false

[functions.brevo-send-template]
verify_jwt = false

[functions.auth-email-sender]
verify_jwt = false

[functions.setup-auth-hook]
verify_jwt = false

[functions.vybbi-ai]
verify_jwt = false

[functions.whatsapp-sender]
verify_jwt = false

[functions.prospect-webhooks]
verify_jwt = false

[functions.create-token-payment]
verify_jwt = true

[functions.verify-token-payment]
verify_jwt = true

[functions.admin-create-venue-profile]
verify_jwt = true

[functions.send-venue-claim-email]
verify_jwt = false

[functions.claim-venue-profile]
verify_jwt = false

[functions.send-representation-invitation]
verify_jwt = true

[functions.get-mapbox-token]
verify_jwt = false