project_id = "fepxacqrrjvnvpgzwhyr"

[functions.send-notification]
verify_jwt = false

[functions.send-system-notification]
verify_jwt = false

[functions.send-prospecting-email]
verify_jwt = false

[functions.send-test-email]
verify_jwt = false

[functions.translate-text]
verify_jwt = false

[functions.brevo-templates]
verify_jwt = false

[functions.brevo-send-template]
verify_jwt = false

[functions.auth-email-sender]
verify_jwt = false