# Configuration Cloudflare Pages pour Vybbi
name = "vybbi"
compatibility_date = "2024-09-28"

[env.production]
name = "vybbi"

[env.preview]
name = "vybbi-preview"

# Configuration pour les Pages Functions si nécessaire
# [build]
# command = "npm run build"
# publish = "dist"

# Variables d'environnement (à configurer dans l'interface Cloudflare)
# VITE_SUPABASE_PROJECT_ID
# VITE_SUPABASE_PUBLISHABLE_KEY  
# VITE_SUPABASE_URL