# Configuration Cloudflare Pages pour Vybbi
name = "vybbi"
compatibility_date = "2024-09-28"

[env.production]
name = "vybbi"

[env.preview]
name = "vybbi-preview"

# Configuration pour forcer l'utilisation de npm au lieu de bun
[build]
command = "npm run build"
publish = "dist"

# Variables d'environnement pour Cloudflare Pages
[env.production.vars]
NODE_VERSION = "22"
NPM_FLAGS = "--legacy-peer-deps"

[env.preview.vars]
NODE_VERSION = "22"
NPM_FLAGS = "--legacy-peer-deps"

# Variables d'environnement Supabase (à configurer dans l'interface Cloudflare)
# VITE_SUPABASE_PROJECT_ID
# VITE_SUPABASE_PUBLISHABLE_KEY  
# VITE_SUPABASE_URL